// Generated by CoffeeScript 1.3.3
(function() {
  var ThanksView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ThanksView = (function(_super) {

    __extends(ThanksView, _super);

    function ThanksView() {
      return ThanksView.__super__.constructor.apply(this, arguments);
    }

    ThanksView.prototype.events = {
      'click .btn.getmore': 'getMoreClicked'
    };

    ThanksView.prototype.render = function() {
      var template;
      template = $('#thanksViewTemplate').html();
      this.$el.append(Mustache.to_html(template));
      return this;
    };

    ThanksView.prototype.getMoreClicked = function() {
      return window.location.hash = "offer";
    };

    return ThanksView;

  })(Backbone.View);

  (typeof exports !== "undefined" && exports !== null ? exports : this).ThanksView = ThanksView;

}).call(this);
